

const data = [
  {
    "img": "https://m.media-amazon.com/images/I/71E75yRwCDL._AC_UY575_.jpg",
    "title": "Pacer Future Sneaker",
    "start": 4,
    "reviews": "123 reviews",
    "prevPrice": 140,
    "newPrice": 150,
    "company": "Puma",
    "color": "red",
    "category": "shoes"
  },
  {
    "img": "https://m.media-amazon.com/images/I/6125yAfsJKL._AC_UX575_.jpg",
    "title": "Nike Air Monarch IV",
    "start": 5,
    "reviews": "33 reviews",
    "prevPrice": 140,
    "newPrice": 135,
    "company": "Nike",
    "color": "white",
    "category": "shoes"
  },
  {
    "img": "https://m.media-amazon.com/images/I/71vYQ546zAL._SL1155_.jpg",
    "title": "NYX Professional Make-Up Eye Shadow Palette",
    "start": 5,
    "reviews": "13 reviews",
    "prevPrice": 40,
    "newPrice": 35,
    "company": "NYX",
    "color": "brown",
    "category": "cosmetics"
  },
  {
    "img": "https://m.media-amazon.com/images/I/7135DSnMj+L._SL1500_.jpg",
    "title": "COSRX Advanced Snail 92% All in One Cream",
    "start": 5,
    "reviews": "13 reviews",
    "prevPrice": 16,
    "newPrice": 15,
    "company": "NYX",
    "color": "white",
    "category": "cosmetics"
  },
  {
    "img": "https://m.media-amazon.com/images/I/71C7E6L-d4L._SL1500_.jpg",
    "title": "Catrice Ultimate Camouflage Cream",
    "start": 5,
    "reviews": "13 reviews",
    "prevPrice": 6,
    "newPrice": 5,
    "company": "NYX",
    "color": "white",
    "category": "cosmetics"
  },
  {
    "img": "https://m.media-amazon.com/images/I/81kj3O-1ylL._AC_SX425_.jpg",
    "title": "Living Crafts - APOLLO Pants Pack of 2",
    "start": 4,
    "reviews": "133 reviews",
    "prevPrice": null,
    "newPrice": 55,
    "company": "Fusion",
    "color": "black",
    "category": "pants"
  },
  {
    "img": "https://m.media-amazon.com/images/I/812bxziO2YL._AC_SL1500_.jpg",
    "title": "Paprika",
    "start": 5,
    "reviews": "123 reviews",
    "prevPrice": 14,
    "newPrice": 12,
    "company": "Seed King",
    "color": "red",
    "category": "vegetable"
  },
  {
    "img": "https://m.media-amazon.com/images/I/71kZzmsx9QL._SL1500_.jpg",
    "title": "BAMELO Fresh Vegetable Box",
    "start": 5,
    "reviews": "93 reviews",
    "prevPrice": 24,
    "newPrice": 12,
    "company": "Seed King",
    "color": "red",
    "category": "vegetable"
  },
  {
    "img": "https://m.media-amazon.com/images/I/4148hjLiTEL.jpg",
    "title": "FRUCHTVERSAND Alexandra Food Potatoes",
    "start": 5,
    "reviews": "293 reviews",
    "prevPrice": 34,
    "newPrice": 12,
    "company": "Seed King",
    "color": "white",
    "category": "vegetable"
  },
  {
    "img": "https://m.media-amazon.com/images/I/912QbpGZCwL._AC_SL1500_.jpg",
    "title": "KESSER® Potato Plant Bag Set of 3 38L",
    "start": 4,
    "reviews": "163 reviews",
    "prevPrice": 74,
    "newPrice": 62,
    "company": "Seed King",
    "color": "black",
    "category": "vegetable"
  },
  {
    "img": "https://m.media-amazon.com/images/I/519MRhRKGFL._AC_UX575_.jpg",
    "title": "Nike Air Vapormax Plus",
    "start": 4,
    "reviews": "123 reviews",
    "prevPrice": 140,
    "newPrice": 100,
    "company": "Nike",
    "color": "red",
    "category": "shoes"
  },
  {
    "img": "https://m.media-amazon.com/images/I/51e+B9l18QL._AC_SX535_.jpg",
    "title": "Nike Men's Air Max Dawn Trainers",
    "start": 4,
    "reviews": "23 reviews",
    "prevPrice": 140,
    "newPrice": 100,
    "company": "Nike",
    "color": "red",
    "category": "shoes"
  },
  {
    "img": "https://m.media-amazon.com/images/I/51+P9uAvb1L._AC_UY695_.jpg",
    "title": "Nike Waffle One Sneaker",
    "start": 5,
    "reviews": "123 reviews",
    "prevPrice": 140,
    "newPrice": 200,
    "company": "Nike",
    "color": "green",
    "category": "shoes"
  },
  {
    "img": "https://m.media-amazon.com/images/I/71oEKkghg-L._AC_UX575_.jpg",
    "title": "Adidas Running Shoe",
    "start": 4,
    "reviews": "123 reviews",
    "prevPrice": 140,
    "newPrice": 90,
    "company": "Adidas",
    "color": "black",
    "category": "shoes"
  },
  {
    "img": "https://m.media-amazon.com/images/I/41M54ztS6IL._AC_SY625._SX._UX._SY._UY_.jpg",
    "title": "Flat Slip On Pumps",
    "start": 4,
    "reviews": "123 reviews",
    "prevPrice": 140,
    "newPrice": 200,
    "company": "Vans",
    "color": "green",
    "category": "shoes"
  },
  {
    "img": "https://m.media-amazon.com/images/I/71zKuNICJAL._AC_UX625_.jpg",
    "title": "Knit Ballet Flat",
    "start": 4,
    "reviews": "123 reviews",
    "prevPrice": 140,
    "newPrice": 50,
    "company": "Adidas",
    "color": "black",
    "category": "shoes"
  },
  {
    "img": "https://m.media-amazon.com/images/I/71pZKVl6cQL._AC_SX425_.jpg",
    "title": "Men’s Performance Pants, Stylish, Slim Fit",
    "start": 5,
    "reviews": "13 reviews",
    "prevPrice": 140,
    "newPrice": 135,
    "company": "Fusion",
    "color": "brown",
    "category": "pants"
  },
  {
    "img": "https://m.media-amazon.com/images/I/61V9APfz97L._AC_UY695_.jpg",
    "title": "Loafer Flats",
    "start": 4,
    "reviews": "123 reviews",
    "prevPrice": 140,
    "newPrice": 50,
    "company": "Vans",
    "color": "white",
    "category": "shoes"
  },
  {
    "img": "https://m.media-amazon.com/images/I/71VaQ+V6XnL._AC_UY695_.jpg",
    "title": "Nike Zoom Freak",
    "start": 4,
    "reviews": "123 reviews",
    "prevPrice": 140,
    "newPrice": 120,
    "company": "Nike",
    "color": "green",
    "category": "shoes"
  },
  {
    "img": "https://m.media-amazon.com/images/I/61-cBsLhJHL._AC_UY695_.jpg",
    "title": "Nike Men's Sneaker",
    "start": 4,
    "reviews": "123 reviews",
    "prevPrice": 140,
    "newPrice": 110,
    "company": "Adidas",
    "color": "blue",
    "category": "shoes"
  },
  {
    "img": "https://m.media-amazon.com/images/I/81xXDjojYKS._AC_UX575_.jpg",
    "title": "PUMA BLACK-OCE",
    "start": 4,
    "reviews": "123 reviews",
    "prevPrice": 140,
    "newPrice": 130,
    "company": "Puma",
    "color": "green",
    "category": "shoes"
  },
  {
    "img": "https://m.media-amazon.com/images/I/71jeoX0rMBL._AC_UX575_.jpg",
    "title": "Unisex-Adult Super",
    "start": 4,
    "reviews": "123 reviews",
    "prevPrice": 140,
    "newPrice": 150,
    "company": "Puma",
    "color": "black",
    "category": "shoes"
  },
  {
    "img": "https://m.media-amazon.com/images/I/61TM6Q9dvxL._AC_UX575_.jpg",
    "title": "Roma Basic Sneaker",
    "start": 4,
    "reviews": "123 reviews",
    "prevPrice": 140,
    "newPrice": 150,
    "company": "Puma",
    "color": "white",
    "category": "shoes"
  },
  {
    "img": "https://m.media-amazon.com/images/I/7128-af7joL._AC_UY575_.jpg",
    "title": "Pacer Future Doubleknit",
    "start": 4,
    "reviews": "123 reviews",
    "prevPrice": 140,
    "newPrice": 150,
    "company": "Puma",
    "color": "black",
    "category": "shoes"
  },
  {
    "img": "https://m.media-amazon.com/images/I/81xXDjojYKS._AC_UX575_.jpg",
    "title": "Fusion Evo Golf Shoe",
    "start": 4,
    "reviews": "123 reviews",
    "prevPrice": 140,
    "newPrice": 100,
    "company": "Puma",
    "color": "green",
    "category": "shoes"
  },
  {
    "img": "https://m.media-amazon.com/images/I/719gdz8lsTS._AC_UX575_.jpg",
    "title": "Rainbow Chex Skate",
    "start": 4,
    "reviews": "123 reviews",
    "prevPrice": 140,
    "newPrice": 100,
    "company": "Vans",
    "color": "red",
    "category": "shoes"
  },
  {
    "img": "https://m.media-amazon.com/images/I/71gpFHJlnoL._AC_UX575_.jpg",
    "title": "Low-Top Trainers",
    "start": 4,
    "reviews": "123 reviews",
    "prevPrice": 140,
    "newPrice": 100,
    "company": "Vans",
    "color": "white",
    "category": "shoes"
  },
  {
    "img": "https://m.media-amazon.com/images/I/71pf7VFs9CL._AC_UX575_.jpg",
    "title": "Vans Unisex Low-Top",
    "start": 4,
    "reviews": "123 reviews",
    "prevPrice": 140,
    "newPrice": 100,
    "company": "Vans",
    "color": "blue",
    "category": "shoes"
  },
  {
    "img": "https://m.media-amazon.com/images/I/61N4GyWcHPL._AC_UY575_.jpg",
    "title": "Classic Bandana Sneakers",
    "start": 4,
    "reviews": "123 reviews",
    "prevPrice": 60,
    "newPrice": 40,
    "company": "Nike",
    "color": "black",
    "category": "shoes"
  },
  {
    "img": "https://m.media-amazon.com/images/I/61bncQ44yML._AC_UX695_.jpg",
    "title": "Chunky High Heel",
    "start": 4,
    "reviews": "123 reviews",
    "prevPrice": 90,
    "newPrice": 35,
    "company": "Vans",
    "color": "black",
    "category": "shoes"
  },
  {
    "img": "https://m.media-amazon.com/images/I/71czu7WgGuL._AC_UY695_.jpg",
    "title": "Slip On Stiletto High Heel",
    "start": 4,
    "reviews": "123 reviews",
    "prevPrice": 70,
    "newPrice": 20,
    "company": "Puma",
    "color": "black",
    "category": "shoes"
  },
  {
    "img": "https://m.media-amazon.com/images/I/510S1B29wCL._AC_SY550_.jpg",
    "title": "Petrol Industries Men's Denim Narrow Suit Trousers",
    "start": 5,
    "reviews": "13 reviews",
    "prevPrice": 59,
    "newPrice": 55,
    "company": "Fusion",
    "color": "jeans",
    "category": "pants"
  },
  {
    "img": "https://m.media-amazon.com/images/I/61men05KRxL._AC_UY625_.jpg",
    "title": "DREAM PAIRS Court Shoes",
    "start": 4,
    "reviews": "123 reviews",
    "prevPrice": 140,
    "newPrice": 150,
    "company": "Nike",
    "color": "red",
    "category": "shoes"
  },
  {
    "img": "https://m.media-amazon.com/images/I/519MRhRKGFL._AC_UX575_.jpg",
    "title": "Nike Air Vapormax Plus",
    "start": 4,
    "reviews": "123 reviews",
    "prevPrice": 140,
    "newPrice": 200,
    "company": "Nike",
    "color": "red",
    "category": "shoes"
  },
  {
    "img": "https://m.media-amazon.com/images/I/51PGWTXgf-L._AC_UY625_.jpg",
    "title": "Low Mid Block Heels",
    "start": 4,
    "reviews": "123 reviews",
    "prevPrice": 140,
    "newPrice": 200,
    "company": "Nike",
    "color": "black",
    "category": "shoes"
  },
  {
    "img": "https://m.media-amazon.com/images/I/616sA5XUKtL._AC_UY675_.jpg",
    "title": "Chunky High Heel",
    "start": 4,
    "reviews": "123 reviews",
    "prevPrice": 140,
    "newPrice": 50,
    "company": "Adidas",
    "color": "black",
    "category": "shoes"
  },
  {
    "img": "https://m.media-amazon.com/images/I/71h5+MbEK7L._AC_UY625_.jpg",
    "title": "Amore Fashion Stilettos",
    "start": 4,
    "reviews": "123 reviews",
    "prevPrice": 140,
    "newPrice": 150,
    "company": "Adidas",
    "color": "white",
    "category": "shoes"
  },
  {
    "img": "https://m.media-amazon.com/images/I/61uw5RDxKQL._AC_UY625_.jpg",
    "title": "Bridal Sandals Glitter",
    "start": 4,
    "reviews": "123 reviews",
    "prevPrice": 140,
    "newPrice": 50,
    "company": "Adidas",
    "color": "black",
    "category": "shoes"
  },
  {
    "img": "https://m.media-amazon.com/images/I/71yhoZP0l6L._AC_UY695_.jpg",
    "title": "Wedding Prom Bridal",
    "start": 4,
    "reviews": "123 reviews",
    "prevPrice": 140,
    "newPrice": 50,
    "company": "Adidas",
    "color": "black",
    "category": "shoes"
  }
]


export default data;
