

// const data = [
//   {
//     "img": "https://m.media-amazon.com/images/I/71E75yRwCDL._AC_UY575_.jpg",
//     "title": "Pacer Future Sneaker",
//     "start": 4,
//     "reviews": "123 reviews",
//     "prevPrice": 140,
//     "newPrice": 150,
//     "company": "Puma",
//     "color": "red",
//     "category": "shoes",
//     "date": "2024-23-14T10:15:00"
//   },
//   {
//     "img": "https://m.media-amazon.com/images/I/6125yAfsJKL._AC_UX575_.jpg",
//     "title": "Nike Air Monarch IV",
//     "description":"This shoe model from Nike is a model from the trainers category. These men's shoes in white impress with a clear design and underline the current shoe fashion. These large shoes from Nike are perfectly adapted to the urban fashion spirit and add the right touch to any modern as well as classic sporty outfit. ",
//     "start": 5,
//     "reviews": "33 reviews",
//     "prevPrice": 140,
//     "newPrice": 135,
//     "company": "Nike",
//     "color": "white",
//     "category": "shoes",
//     "date": "2024-22-14T10:15:00"
//   },
//   {
//     "img": "https://m.media-amazon.com/images/I/71vYQ546zAL._SL1155_.jpg",
//     "title": "NYX Professional Make-Up",
//     "description":"Palette of 16 high-quality eye shadows in warm and earthy tones with shimmering, matte and metallic finish, highly pigmented and long-lasting colours. The result: Colour-intensive and individual eye shadow looks, creative and unique combinations of matte, shimmering metallic tones without staining and smudging.",
//     "start": 5,
//     "reviews": "13 reviews",
//     "prevPrice": 40,
//     "newPrice": 35,
//     "company": "NYX",
//     "color": "brown",
//     "category": "cosmetics",
//     "date": "2024-04-14T10:15:00"
//   },
//   {
//     "img": "https://m.media-amazon.com/images/I/7135DSnMj+L._SL1500_.jpg",
//     "title": "COSRX Advanced Snail 92% All in One Cream",
//     "start": 5,
//     "reviews": "13 reviews",
//     "description": "Feuchtigkeitsspendende Gesichtscreme mit Schneckenschleim und Hyaluronsäure für trockene und sensible Haut. Hocheffektive reparierende Feuchtigkeitspflege: Eine leichte Creme, die irritierte, gereizte Haut nach Ausbrüchen von Rosazea und dergleichen beruhigt und regeneriert.",
//     "prevPrice": 16,
//     "newPrice": 15,
//     "company": "NYX",
//     "color": "white",
//     "category": "cosmetics",
//     "date": "2024-06-14T10:15:00"
//   },
//   {
//     "img": "https://m.media-amazon.com/images/I/71C7E6L-d4L._SL1500_.jpg",
//     "title": "Catrice Ultimate Camouflage Cream",
//     "start": 5,
//     "reviews": "13 reviews",
//     "description": "Reliably conceals impurities and redness. Long lasting texture. Non-comedogenic. Vegan, perfume, alcohol, parabens, microplastic particles, nanoparticles free, gluten-free, acetone-free. We say no to animal testing. Cosnova is internationally listed with essence and CATRICE at PETA Germany as well as PETA.",
//     "prevPrice": 6,
//     "newPrice": 5,
//     "company": "NYX",
//     "color": "white",
//     "category": "cosmetics",
//     "date": "2024-08-14T10:15:00"
//   },
//   {
//     "img": "https://m.media-amazon.com/images/I/81kj3O-1ylL._AC_SX425_.jpg",
//     "title": "Living Crafts - APOLLO Pants Pack of 2",
//     "start": 4,
//     "reviews": "133 reviews",
//     "description": "Sporty fit that shapes a dynamic silhouette while providing optimal comfort. Wide attached elastic band at waistband for a secure, comfortable fit and excellent fit. Convenient side fly for easy on and off and added comfort. High quality double stitching on the hem of the leg cuffs for durability and a clean, professional finish.",
//     "prevPrice": 75,
//     "newPrice": 55,
//     "company": "Fusion",
//     "color": "black",
//     "category": "pants",
//     "date": "2024-07-14T10:15:00"
//   },
//   {
//     "img": "https://m.media-amazon.com/images/I/812bxziO2YL._AC_SL1500_.jpg",
//     "title": "Paprika",
//     "start": 5,
//     "reviews": "123 reviews",
//     "description": "Pepper pepper: the mild 15 - 18 cm long, icicle-shaped fruits ripen from green to deep red. They are tasty and vitamin-rich. Premium: Pepper seeds are quality pepper seeds are vegetables from traditional plant breeding without the use of genetic engineering. Versatile: Pepper seeds are also fun for children in the raised bed, balcony box, greenhouse on the windowsill and of course also in the garden in the normal vegetable patch.", 
//     "prevPrice": 14,
//     "newPrice": 12,
//     "company": "Seed King",
//     "color": "red",
//     "category": "vegetable",
//     "date": "2024-09-14T10:15:00"
//   },
//   {
//     "img": "https://m.media-amazon.com/images/I/71kZzmsx9QL._SL1500_.jpg",
//     "title": "BAMELO Fresh Vegetable Box",
//     "start": 5,
//     "reviews": "93 reviews",
//     "description": "Our fresh vegetable box consists of a healthy selection of ripe seasonal vegetables. With lots of rich fruit varieties, you will find a vitamin-rich and delicious variety of cucumbers, tomatoes, parika, zuchini, aubergine, kohlrabi, carrots, root petersile, iceberg salad, potatoes, onions, lemons, fennel and seasonal fruit varieties. We do our best by putting together only the best fruits for you and getting them fit through the week.100% plastic-free packaging",
//     "prevPrice": 24,
//     "newPrice": 12,
//     "company": "Seed King",
//     "color": "red",
//     "category": "vegetable",
//     "date": "2024-10-14T10:15:00"
//   },
//   {
//     "img": "https://m.media-amazon.com/images/I/4148hjLiTEL.jpg",
//     "title": "FRUCHTVERSAND Alexandra Food Potatoes",
//     "start": 5,
//     "reviews": "293 reviews",
//     "description":"Untreated and unwashed. Food potatoes (heather potatoes) from the Lüneburg Heath from controlled integrated cultivation. Storable premium quality directly from the producer farm Hof Lüdemann. Top sorting - quality level (commercial class) EXTRA according to Berlin agreements", 
//     "prevPrice": 34,
//     "newPrice": 12,
//     "company": "Seed King",
//     "color": "white",
//     "category": "vegetable",
//     "date": "2024-12-14T10:15:00"
//   },
//   {
//     "img": "https://m.media-amazon.com/images/I/912QbpGZCwL._AC_SL1500_.jpg",
//     "title": "KESSER® Potato Plant Bag Set of 3 38L",
//     "start": 4,
//     "reviews": "163 reviews",
//     "description": "Maximum durability: the KESSER potato planting bag is a durable and reliable tool for your gardening. Made from high quality non-woven fabric and reinforced seams, this sack offers maximum durability that can withstand the demands of gardening. You can rest assured that it will serve you faithfully for many growing seasons.", 
//     "prevPrice": 74,
//     "newPrice": 62,
//     "company": "Seed King",
//     "color": "black",
//     "category": "vegetable",
//     "date": "2024-11-14T10:15:00"
//   },
//   {
//     "img": "https://m.media-amazon.com/images/I/519MRhRKGFL._AC_UX575_.jpg",
//     "title": "Nike Air Vapormax Plus",
//     "start": 4,
//     "reviews": "123 reviews",
//      "description":"37% cotton, 36% polyacrylic, 17% polyamide, 6% polyester, 4% elastodiene.",
//     "prevPrice": 140,
//     "newPrice": 100,
//     "company": "Nike",
//     "color": "red",
//     "category": "shoes",
//     "date": "2024-13-14T10:15:00"
//   },
//   {
//     "img": "https://m.media-amazon.com/images/I/51e+B9l18QL._AC_SX535_.jpg",
//     "title": "Nike Men's Air Max Dawn Trainers",
//     "start": 4,
//     "reviews": "23 reviews",
//      "description": "Nike sports shoe. Durable and lightweight. Foam midsole for long-lasting cushioning.", 
//     "prevPrice": 140,
//     "newPrice": 100,
//     "company": "Nike",
//     "color": "red",
//     "category": "shoes",
//     "date": "2024-14-14T10:15:00"
//   },
//   {
//     "img": "https://m.media-amazon.com/images/I/51+P9uAvb1L._AC_UY695_.jpg",
//     "title": "Nike Waffle One Sneaker",
//     "start": 5,
//     "reviews": "123 reviews",
//     "description": "Outer Material: Synthetic. Closure: Lace-Up. Heel Type: Flat. Shoe Width: Medium",
//     "prevPrice": 140,
//     "newPrice": 200,
//     "company": "Nike",
//     "color": "green",
//     "category": "shoes",
//     "date": "2024-15-14T10:15:00"
//   },
//   {
//     "img": "https://m.media-amazon.com/images/I/71oEKkghg-L._AC_UX575_.jpg",
//     "title": "Adidas Running Shoe",
//     "start": 4,
//     "reviews": "123 reviews",
//     "description": "Regular fit. Laces. Textile lining. Cloudfoam midsole", 
//     "prevPrice": 140,
//     "newPrice": 90,
//     "company": "Adidas",
//     "color": "black",
//     "category": "shoes",
//     "date": "2024-16-14T10:15:00"
//   },
//   {
//     "img": "https://m.media-amazon.com/images/I/41M54ztS6IL._AC_SY625._SX._UX._SY._UY_.jpg",
//     "title": "Flat Slip On Pumps",
//     "start": 4,
//     "reviews": "123 reviews",
//     "description": "Easy to wear: ZZS women's slip-on flat shoes have an elastic cuff with a pull tab on the back makes them easy to put on and take off. Knitted material is not too tight around the foot, but is tight enough that it feels secure on your foot. Lightweight and comfortable flats shoes: ZZS casual flats for women use skin-friendly knitted mesh, keep your feet cool and comfortable even for a long time walking or working.",
//     "prevPrice": 140,
//     "newPrice": 200,
//     "company": "Vans",
//     "color": "green",
//     "category": "shoes",
//     "date": "2024-17-14T10:15:00"
//   },
//   {
//     "img": "https://m.media-amazon.com/images/I/71zKuNICJAL._AC_UX625_.jpg",
//     "title": "Knit Ballet Flat",
//     "start": 4,
//     "reviews": "123 reviews",
//     "description": "Ballet shoes for women and girls: Ofoot style slippers with cute animal embroidery, charcoal, black owl, grey rat. Your loved ones at parties, holidays or festivals. Sole made of TPR rubber, foldable, non-slip and portable for outdoor use: the non-slip sole made of TPR is suitable for indoor use, also ideal for occasional trips. The inserts are ideal for use in the letterbox, in the garage or in the laundry room. Lightweight and foldable for travel, spa, work or hospital.", 
//     "prevPrice": 100,
//     "newPrice": 50,
//     "company": "Adidas",
//     "color": "black",
//     "category": "shoes",
//     "date": "2024-18-14T10:15:00"
//   },
//   {
//     "img": "https://m.media-amazon.com/images/I/71pZKVl6cQL._AC_SX425_.jpg",
//     "title": "Men’s Performance Pants, Stylish, Slim Fit",
//     "start": 5,
//     "reviews": "13 reviews",
//     "description": "Stylish, comfortable and affordable: our performance trousers have a stylish look and unsurpassed functionality, so you can enjoy excellent comfort when wearing them. Exceptional comfort – unlike ordinary trousers and jeans, performance trousers are equipped with a light stretch effect so that the wearer experiences optimal comfort when worn", 
//     "prevPrice": 140,
//     "newPrice": 135,
//     "company": "Fusion",
//     "color": "brown",
//     "category": "pants",
//     "date": "2024-19-14T10:15:00"
//   },
//   {
//     "img": "https://m.media-amazon.com/images/I/61V9APfz97L._AC_UY695_.jpg",
//     "title": "Loafer Flats",
//     "start": 4,
//     "reviews": "123 reviews",
//     "description": "Stylish, comfortable and affordable: our performance trousers have a stylish look and unsurpassed functionality, so you can enjoy excellent comfort when wearing them. Exceptional comfort – unlike ordinary trousers and jeans, performance trousers are equipped with a light stretch effect so that the wearer experiences optimal comfort when worn", 
//     "prevPrice": 80,
//     "newPrice": 50,
//     "company": "Vans",
//     "color": "white",
//     "category": "shoes",
//     "date": "2024-20-14T10:15:00"
//   },
//   {
//     "img": "https://m.media-amazon.com/images/I/71VaQ+V6XnL._AC_UY695_.jpg",
//     "title": "Nike Zoom Freak",
//     "start": 4,
//     "reviews": "123 reviews",
//      "description":"Ultra padded tongue feels incredibly soft. Leather adds durability while perforations at the top provide an airy aesthetic. The raised foam midsole and moulded heel provide modern comfort",
//     "prevPrice": 140,
//     "newPrice": 120,
//     "company": "Nike",
//     "color": "green",
//     "category": "shoes",
//     "date": "2024-21-14T10:15:00"
//   },
//   {
//     "img": "https://m.media-amazon.com/images/I/61-cBsLhJHL._AC_UY695_.jpg",
//     "title": "Nike Men's Sneaker",
//     "start": 4,
//     "reviews": "123 reviews",
//      "description":"Simple and simple details. Leather and faux leather upper material. Embroidered swoosh design. Perforations on toes and sides",
//     "prevPrice": 140,
//     "newPrice": 110,
//     "company": "Adidas",
//     "color": "blue",
//     "category": "shoes",
//     "date": "2024-22-14T10:15:00"
//   },
//   {
//     "img": "https://m.media-amazon.com/images/I/81xXDjojYKS._AC_UX575_.jpg",
//     "title": "PUMA BLACK-OCE",
//     "start": 4,
//     "reviews": "123 reviews",
//      "description":"Suede upper. Full-length lacing for a secure fit. Cushioning midsole for comfort.",
//     "prevPrice": 140,
//     "newPrice": 130,
//     "company": "Puma",
//     "color": "green",
//     "category": "shoes",
//     "date": "2024-23-14T10:15:00"
//   },
//   {
//     "img": "https://m.media-amazon.com/images/I/71jeoX0rMBL._AC_UX575_.jpg",
//     "title": "Unisex-Adult Super",
//     "start": 4,
//     "reviews": "123 reviews",
//      "description":"Upper made from soft leather. Advanced outsole with clear design. Timeless classics.",
//     "prevPrice": 145,
//     "newPrice": 150,
//     "company": "Puma",
//     "color": "black",
//     "category": "shoes",
//     "date": "2024-24-14T10:15:00"
//   },
//   {
//     "img": "https://m.media-amazon.com/images/I/61TM6Q9dvxL._AC_UX575_.jpg",
//     "title": "Roma Basic Sneaker",
//     "start": 4,
//     "reviews": "123 reviews",
//      "description":"Retro inspired sneaker with moulded strips on the sides and T-toe overlay. Padded midsole with arch support. Outsole with saw-tooth traction",
//     "prevPrice": 160,
//     "newPrice": 150,
//     "company": "Puma",
//     "color": "white",
//     "category": "shoes",
//     "date": "2024-25-14T10:15:00"
//   },
//   {
//     "img": "https://m.media-amazon.com/images/I/7128-af7joL._AC_UY575_.jpg",
//     "title": "Pacer Future Doubleknit",
//     "start": 4,
//     "reviews": "123 reviews",
//      "description":"Two-tone knit upper. SoftFoam+ insole. EVA midsole. Non-marking rubber outsole",
//     "prevPrice": 140,
//     "newPrice": 150,
//     "company": "Puma",
//     "color": "black",
//     "category": "shoes",
//     "date": "2024-26-14T10:15:00"
//   },
//   {
//     "img": "https://m.media-amazon.com/images/I/81xXDjojYKS._AC_UX575_.jpg",
//     "title": "Fusion Evo Golf Shoe",
//     "start": 4,
//     "reviews": "123 reviews",
//      "description":"Boot construction provides comfort and 360 degree support around the foot. PWRSTRAP FIT SYSTEM: Advanced nylon webbing integrated with the lacing system that wraps around the foot to ensure a secure, custom fit.Softfoam dual density insole provides two unique layers of padding for individual comfort, fit and long durability.",
//     "prevPrice": 110,
//     "newPrice": 90,
//     "company": "Puma",
//     "color": "green",
//     "category": "shoes",
//     "date": "2024-27-14T10:15:00"
//   },
//   {
//     "img": "https://m.media-amazon.com/images/I/719gdz8lsTS._AC_UX575_.jpg",
//     "title": "Rainbow Chex Skate",
//     "start": 4,
//     "reviews": "123 reviews",
//      "description":" Vans. Unisex Shoes. Slip on shoes. Checkerboard Black/Classic",
//     "prevPrice": 180,
//     "newPrice": 150,
//     "company": "Vans",
//     "color": "red",
//     "category": "shoes",
//     "date": "2024-28-14T10:15:00"
//   },
//   {
//     "img": "https://m.media-amazon.com/images/I/71gpFHJlnoL._AC_UX575_.jpg",
//     "title": "Low-Top Trainers",
//     "start": 4,
//     "reviews": "123 reviews",
//      "description":"Stilvoll und vielseitig: Schwarze Sneaker gehören zu den vielseitigsten und stilvollsten Schuharten, die zu fast jedem Anlass und Outfit passen. Hohe Qualität: Dank des verwendeten weichen und strapazierfähigen Ledermaterials bieten diese Sneaker einen tollen Tragekomfort für den ganzen Tag und die Qualität der verwendeten Materialien und Verarbeitung zeigt sich in Details wie präzisen Nähten, griffiger Sohle aus TPR oder exzellenter Verarbeitung hochwertige Schnürsenkel",
//     "prevPrice": 140,
//     "newPrice": 110,
//     "company": "Vans",
//     "color": "white",
//     "category": "shoes",
//     "date": "2024-29-14T10:15:00"
//   },
//   {
//     "img": "https://m.media-amazon.com/images/I/71pf7VFs9CL._AC_UX575_.jpg",
//     "title": "Vans Unisex Low-Top",
//     "start": 4,
//     "reviews": "123 reviews",
//      "description":"Very comfortable to wear. Comfortable fit thanks to padded shoe collar. Robust leather upper material. High-quality outer sole in a traditional design. Slip-on for easy on and off",
//     "prevPrice": 120,
//     "newPrice": 100,
//     "company": "Vans",
//     "color": "blue",
//     "category": "shoes",
//     "date": "2024-30-14T10:15:00"
//   },
//   {
//     "img": "https://m.media-amazon.com/images/I/61N4GyWcHPL._AC_UY575_.jpg",
//     "title": "Classic Bandana Sneakers",
//     "start": 4,
//     "reviews": "123 reviews",
//      "description":"You can put them on and take them off very quickly. Simple and convenient.The ultra-light design makes it easier for you to meet different occasions in your life and act faster. The elastic and breathable mesh upper is designed with fine weaves for more comfort.",
//     "prevPrice": 60,
//     "newPrice": 40,
//     "company": "Nike",
//     "color": "black",
//     "category": "shoes",
//     "date": "2024-31-14T10:15:00"
//   },
//   {
//     "img": "https://m.media-amazon.com/images/I/61bncQ44yML._AC_UX695_.jpg",
//     "title": "Chunky High Heel",
//     "start": 4,
//     "reviews": "123 reviews",
//      "description":"Flower slip-on sandals: these flower sandals are slip-on with elastic ankle strap, which is easy to put on and take off. The flower upper embellishes your feet and looks particularly slim and fashionable. Perfect sandals: Take style inspiration from the most coveted summer casual shoes, perfect to complement your fashion aesthetic with stylish simplicity. Women's comfort sandals make your summer more fun and enjoyable. Slip-on sandals for women's summer look",
//     "prevPrice": 90,
//     "newPrice": 35,
//     "company": "Vans",
//     "color": "black",
//     "category": "shoes",
//     "date": "2024-01-14T10:15:00"
//   },
//   {
//     "img": "https://m.media-amazon.com/images/I/71czu7WgGuL._AC_UY695_.jpg",
//     "title": "Slip On Stiletto High Heel",
//     "start": 4,
//     "reviews": "123 reviews",
//      "description":"Microfibre material and comfortable lining, normal shoe width. Classic platform pump high heels with a heel height of 4 inches or 10 cm. Classic stilettos pumps, sexy and comfortable design, excellent workmanship. NobleOnly - Shoes have a durable, non-slip outsole that can improve walking stability. Suitable for many occasions",
//     "prevPrice": 70,
//     "newPrice": 20,
//     "company": "Puma",
//     "color": "black",
//     "category": "shoes",
//     "date": "2024-02-14T10:15:00"
//   },
//   {
//     "img": "https://m.media-amazon.com/images/I/510S1B29wCL._AC_SY550_.jpg",
//     "title": "Petrol Industries Men's Denim Narrow Suit Trousers",
//     "start": 5,
//     "reviews": "13 reviews",
//      "description":"94% Cotton, 3% Polyester. Comfortable thanks to top quality: the selection and use of high-quality fibres in the production of jeans and trousers for men allow a comfortable fit. Details and highlights: slim fit 6-pocket jean with a concealed second coin pocket and is crafted from comfortable stretch denim with a subtle wash",
//     "prevPrice": 59,
//     "newPrice": 55,
//     "company": "Fusion",
//     "color": "jeans",
//     "category": "pants",
//     "date": "2024-03-14T10:15:00"
//   },
//   {
//     "img": "https://m.media-amazon.com/images/I/61men05KRxL._AC_UY625_.jpg",
//     "title": "DREAM PAIRS Court Shoes",
//     "start": 4,
//     "reviews": "123 reviews",
//      "description":"SUPPORTIVE INSOLE The 3-layer insole is covered with skin-friendly fabric and consists of a soft foam middle layer and a breathable latex layer that provides supportive effect. Shoe size runs a little small, as we do not have a half size, we recommend taking one size larger.",
//     "prevPrice": 140,
//     "newPrice": 150,
//     "company": "Nike",
//     "color": "red",
//     "category": "shoes",
//     "date": "2024-04-14T10:15:00"
//   },
//   {
//     "img": "https://m.media-amazon.com/images/I/519MRhRKGFL._AC_UX575_.jpg",
//     "title": "Nike Air Vapormax Plus",
//     "start": 4,
//     "reviews": "123 reviews",
//      "description":"37% cotton, 36% polyacrylic, 17% polyamide, 6% polyester, 4% elastodiene.",
//     "prevPrice": 140,
//     "newPrice": 200,
//     "company": "Nike",
//     "color": "red",
//     "category": "shoes",
//     "date": "2024-05-14T10:15:00"
//   },
//   {
//     "img": "https://m.media-amazon.com/images/I/51PGWTXgf-L._AC_UY625_.jpg",
//     "title": "Low Mid Block Heels",
//     "start": 4,
//     "reviews": "123 reviews",
//      "description":"Heel height: 4 cm, upper material: suede, inner material: PU, materials. the size of the shoe is shown by the Chinese size.Please refer to the shoe size and choose the right size of the shoe according to the foot length.Thank you if you are not so sure that you are about SizeSeadaquat, please tell us about the length and width of your feet. We offer the suggestion to help you. Features: fashion shoe for women, this is the gift for a friend, girlfriend, mother or daughter...",
//     "prevPrice": 140,
//     "newPrice": 200,
//     "company": "Nike",
//     "color": "black",
//     "category": "shoes",
//     "date": "2024-06-14T10:15:00"
//   },
//   {
//     "img": "https://m.media-amazon.com/images/I/71kDnFxCEkL._SL1500_.jpg",
//     "title": "Batana Oil for Hair Cold Pressed",
//     "start": 5,
//     "reviews": "23 reviews",
//      "description":" Stimulates Hair Growth: Our Batana hair oil is rich in vitamin E and Omega-6 with powerful properties. It helps to improve scalp health and support hair growth while thicker, longer and shine. Nourish & Moisturize Hair: Batana oil promotes hair growth and provides a natural shine and moisture, allows the scalp to moisturise and replenish damaged hair, leaving your hair feeling soft and manageable.",
//     "prevPrice": 20,
//     "newPrice": 15,
//     "company": "NYX",
//     "color": "red",
//     "category": "cosmetics",
//     "date": "2024-07-14T10:15:00"
//   },
//   {
//     "img": "https://m.media-amazon.com/images/I/616sA5XUKtL._AC_UY675_.jpg",
//     "title": "Chunky High Heel",
//     "start": 4,
//     "reviews": "123 reviews",
//      "description":"Flower slip-on sandals: these flower sandals are slip-on with elastic ankle strap, which is easy to put on and take off. The flower upper embellishes your feet and looks particularly slim and fashionable. Perfect sandals: Take style inspiration from the most coveted summer casual shoes, perfect to complement your fashion aesthetic with stylish simplicity. ",
//     "prevPrice": 140,
//     "newPrice": 50,
//     "company": "Adidas",
//     "color": "black",
//     "category": "shoes",
//     "date": "2024-08-14T10:15:00"
//   },
//   {
//     "img": "https://m.media-amazon.com/images/I/71h5+MbEK7L._AC_UY625_.jpg",
//     "title": "Amore Fashion Stilettos",
//     "start": 4,
//     "reviews": "123 reviews",
//      "description":"TIMELESS AND STYLISH - With a stylish open toe, crisscross strap and zip, the sandals are absolutely on trend and are ideal for effortless and easy dressing. Emphasise your legs - perfect for a feminine and fashion-conscious look. Wear the sandals with dresses, skinny jeans, leggings and skirts to accentuate your legs.",
//     "prevPrice": 140,
//     "newPrice": 150,
//     "company": "Adidas",
//     "color": "white",
//     "category": "shoes",
//     "date": "2024-23-14T10:15:00"
//   },
//   {
//     "img": "https://m.media-amazon.com/images/I/61uw5RDxKQL._AC_UY625_.jpg",
//     "title": "Bridal Sandals Glitter",
//     "start": 4,
//     "reviews": "123 reviews",
//      "description":"Ladies Slip On Flip Flop Wedge Style PU Thong With Bling Upper. Decorated with the beautiful glittering rhinestones the jeweled 1.8 inch high heel flip flops make great.These are durable and fashionable sandals for women, which can be easily combined with jeans/dresses/trousers/shorts, suitable for any occasion in everyday life, and suitable for indoor and outdoor use, pool, beach, park, party, etc.",
//     "prevPrice": 140,
//     "newPrice": 50,
//     "company": "Adidas",
//     "color": "black",
//     "category": "shoes",
//     "date": "2024-18-14T10:15:00"
//   },
//   {
//     "img": "https://m.media-amazon.com/images/I/51-iAP5RDLL._AC_SY500_.jpg",
//     "title": "adidas Women's Eastrail 2.0 Outdoor",
//     "start": 4,
//     "reviews": "123 reviews",
//      "description":"Regular fit. Lace-ups. Upper made of mesh and synthetic",
//     "prevPrice": 140,
//     "newPrice": 50,
//     "company": "Adidas",
//     "color": "black",
//     "category": "shoes",
//     "date": "2024-04-14T10:15:00"
//   },
//     {
//     "img": "https://m.media-amazon.com/images/I/71kDnFxCEkL._SL1500_.jpg",
//     "title": "Batana Oil for Hair Cold Pressed",
//     "description": "Batana oil is extracted from the seeds of the Batana tree and has been considered an insider tip for healthy and strong hair for centuries. Regular use of this oil can help make hair look healthier, shinier and smoother.",
//     "start": 5,
//     "reviews": "23 reviews",
//     "prevPrice": 20,
//     "newPrice": 15,
//     "company": "NYX",
//     "color": "red",
//     "category": "cosmetics",
//     "date": "2024-08-14T10:15:00"
//   }
// ]


// export default data;
